CACHE_FOLDER=%REGION_HOME%/Cache
EXPORT_FOLDER=//10.15.235.21/fews_exchange/Export
IMPORT_FOLDER=/mnt/fews_exchange/Import
IMPORT_BACKUP_FOLDER=/mnt/fews_exchange/ImportBackup
IMPORT_FAILED_FOLDER=/mnt/fews_exchange/ImportFailed
REPORT_ROOT_DIR=//10.15.235.21/fews_exchange/Reports
GA_DUMPFILEDIR=//10.15.235.21/fews_exchange/DumpFiles

ARCHIVE_FOLDER=//10.15.235.21/fews_archive/archive
ARCHIVE_DOWNLOAD_FOLDER=%REGION_HOME%/Archive
ARCHIVE_WEBSERVICE_URL=http://10.15.235.21:8080/deltares-archive-server/catalogue
ARCHIVE_CATALOGUE_URL=http://10.15.235.21:8080/deltares-archive-server/catalogue
ARCHIVE_ELASTICSEARCHURL=http://10.15.235.21.it:8080/deltares-archive-server/elastic
ARCHIVE_FILESERVICE_URL=http://10.15.235.21:8080/thredds/fileServer/data

EXPLORER_SYSTEMCAPTION=PAT Forecasting System
EXPLORER_HTML_VIEWER=C:/Program Files/Internet Explorer/iexplore.exe
REPORT_EXPORTROOTDIR=%REGION_HOME%/Reports
REPORT_EXPORTZIPDIR=%REGION_HOME%/Reports
REPORT_TEMPLATE_DIR=%REGION_HOME%/config/ReportTemplateFiles
REPORT_ROOT_DIR=%REGION_HOME%/Reports
REGION_HOME_DIR=%REGION_HOME%

GA_MIKE11_ADAPTER=C:/Program Files (x86)/DHI/2020/bin/x64/DHI.Engines.Mike11.RuntimeAdaptor.exe

DEFAULT_EXPIRY_DAYS=30

REPORTS_LOCALMCID=mc00
REPORTS_LEFTCOLMCID=mc00

docking=true
