EXPLORER_SYSTEMCAPTION=PAT Forecasting System
DEFAULT_EXPIRY_DAYS=365

ARCHIVE_CATALOGUE_URL=http://10.15.235.21:8080/deltares-archive-server/catalogue
ARCHIVE_ELASTICSEARCHURL=http://10.15.235.21:8080/deltares-archive-server/elastic
CACHE_FOLDER=%REGION_HOME%/Cache
MapLayersCacheFolder=%REGION_HOME%/MapLCache

REPORTS_LOCALMCID=mc00
REPORTS_LEFTCOLMCID=mc00
